// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBPOv27EnBDfZM9MkHdStJ1O5t2episFts',
    appId: '1:829833925751:web:7ffde19f564e4fc2536272',
    messagingSenderId: '829833925751',
    projectId: 'akijtask',
    authDomain: 'akijtask.firebaseapp.com',
    storageBucket: 'akijtask.firebasestorage.app',
    measurementId: 'G-V705F05MMF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBRXzS0N0txHGLp0DqpCbhhHW5_ipaemD0',
    appId: '1:829833925751:android:3b91b239f3351308536272',
    messagingSenderId: '829833925751',
    projectId: 'akijtask',
    storageBucket: 'akijtask.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDTUyl3wNNrWa2ppxO7UhkBAlFDMZnlbyY',
    appId: '1:829833925751:ios:3269e535f38f21d0536272',
    messagingSenderId: '829833925751',
    projectId: 'akijtask',
    storageBucket: 'akijtask.firebasestorage.app',
    iosBundleId: 'com.example.akijTask',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDTUyl3wNNrWa2ppxO7UhkBAlFDMZnlbyY',
    appId: '1:829833925751:ios:3269e535f38f21d0536272',
    messagingSenderId: '829833925751',
    projectId: 'akijtask',
    storageBucket: 'akijtask.firebasestorage.app',
    iosBundleId: 'com.example.akijTask',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBPOv27EnBDfZM9MkHdStJ1O5t2episFts',
    appId: '1:829833925751:web:ce25c1984b3a4639536272',
    messagingSenderId: '829833925751',
    projectId: 'akijtask',
    authDomain: 'akijtask.firebaseapp.com',
    storageBucket: 'akijtask.firebasestorage.app',
    measurementId: 'G-EN57M25KZT',
  );
}
